// font_6x10.cpp — definition of the bring-up 6x10 ASCII bitmap font.
//
// PARITY: rlvgl/core/src/bitmap_font.rs:109 (FONT_6X10) and the
//         shared glyph blob at src/fonts/font_6x10.bin.
//
// The 713-byte glyph data is materialised by CMake-time hex
// conversion of font_6x10.bin into font_6x10_data.inc; this TU
// includes the inc and constructs a BitmapFont referencing it.

#include "lvglpp/core/fonts/font_6x10.hpp"

#include "font_6x10_data.inc"  // generated by CMake into BUILD_DIR/generated/

namespace lvglpp::core::fonts {

const BitmapFont FONT_6X10 = BitmapFont{
    /*.glyph_width  =*/ 6,
    /*.glyph_height =*/ 10,
    /*.scale        =*/ 2,
    /*.data         =*/ std::span<const std::uint8_t>(
                            detail::FONT_6X10_BYTES.data(),
                            detail::FONT_6X10_BYTES.size()),
};

}  // namespace lvglpp::core::fonts
