#!/usr/bin/env python3
"""gen_i18n.py — compile locales/*.json into RLTN v1 + generated C++.

PARITY: rlvgl/i18n/build.rs (v0.2.0 @ 79f730d). The RLTN blob bytes
MUST be identical to build.rs output for identical inputs — this is
the cross-language contract (docs/i18n/00-rltn-core.md §5.1/§5.2),
locked by the golden test in i18n/tests/.

Emission backends (docs/i18n/00 §5.3, docs/i18n/01 §5.1):
  keys  — <name>.hpp: Locale/Key enum classes, locale_name/tag_name,
          consteval key("...") with compile-time unknown-key error.
  rltn  — <name>_rltn.inc (blob byte array, included by <name>.hpp)
          + <name>.bin (the standalone blob, media-copyable).
  lv    — <name>_lv.hpp: lv_translation static-pack arrays + inline
          bridge wrappers (requires LV_USE_TRANSLATION).

Usage:
  gen_i18n.py --locales DIR --out DIR --name NAME
              [--namespace NS] [--emit keys,rltn,lv]
"""

import argparse
import json
import struct
import sys
from pathlib import Path

BLOB_MAGIC = b"RLTN"
BLOB_VERSION = 1
HEADER_SIZE = 8
ENTRY_SIZE = 6


def to_pascal(key: str) -> str:
    """Mirror build.rs:25–39 to_pascal exactly."""
    out = []
    upper_next = True
    for ch in key:
        if ch in "._-":
            upper_next = True
        elif upper_next:
            out.append(ch.upper())
            upper_next = False
        else:
            out.append(ch)
    return "".join(out)


def load_locales(locales_dir: Path):
    """Mirror build.rs:41–99: sorted files, default = first, fallback fill."""
    files = sorted(p for p in locales_dir.iterdir() if p.suffix == ".json")
    if not files:
        sys.exit(f"error: no locale JSON files found in {locales_dir}")

    locales = []
    for path in files:
        raw = json.loads(path.read_text(encoding="utf-8"))
        for k, v in raw.items():
            if not isinstance(v, str):
                sys.exit(f'error: value for key "{k}" in {path} must be a string')
        # BTreeMap order == lexicographic by code point == python sorted().
        locales.append((path.stem, dict(sorted(raw.items()))))

    default_name, default_map = locales[0]
    default_keys = list(default_map.keys())

    for name, mapping in locales[1:]:
        for key in default_keys:
            if key not in mapping:
                print(
                    f'warning: i18n key "{key}" missing from {name}.json, '
                    "using fallback",
                    file=sys.stderr,
                )
                mapping[key] = default_map[key]
        extra = set(mapping) - set(default_keys)
        for key in sorted(extra):
            # build.rs silently drops these; warn (tool-output delta
            # only — blob bytes unaffected, docs/i18n/00 §5.2).
            print(
                f'warning: i18n key "{key}" only in {name}.json, '
                f"not in {default_name}.json — dropped",
                file=sys.stderr,
            )
    return locales, default_keys


def build_blob(locales, keys) -> bytes:
    """Mirror build.rs:103–139 byte for byte."""
    num_locales = len(locales)
    num_keys = len(keys)

    string_data = bytearray()
    entries = []
    for _name, mapping in locales:
        for key in keys:
            val = mapping[key].encode("utf-8")
            entries.append((len(string_data), len(val)))
            string_data.extend(val)

    blob = bytearray()
    blob.extend(BLOB_MAGIC)
    blob.append(BLOB_VERSION)
    blob.append(num_locales)
    blob.extend(struct.pack("<H", num_keys))
    for offset, length in entries:
        blob.extend(struct.pack("<IH", offset, length))
    blob.extend(string_data)
    return bytes(blob)


def cxx_escape(s: str) -> str:
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    return "".join(out)


GENERATED_NOTE = "// Generated by i18n/tools/gen_i18n.py — do not edit.\n"


def emit_keys_header(locales, keys, name, namespace, emit_rltn):
    locale_variants = []
    seen = set()
    for lname, _ in locales:
        v = to_pascal(lname)
        if v in seen:
            sys.exit(f"error: locale name collision: {lname} -> {v}")
        seen.add(v)
        locale_variants.append((v, lname))

    key_variants = []
    seen = set()
    for k in keys:
        v = to_pascal(k)
        if v in seen:
            sys.exit(
                f'error: i18n key collision: "{k}" maps to variant {v} '
                "which already exists"
            )
        seen.add(v)
        key_variants.append((v, k))

    o = [GENERATED_NOTE]
    o.append("// PARITY: rlvgl generated translations.rs "
             "(rlvgl/i18n/build.rs, v0.2.0 @ 79f730d).\n")
    o.append("#pragma once\n\n")
    o.append("#include <cstdint>\n#include <string_view>\n")
    if emit_rltn:
        o.append('\n#include "lvglpp/i18n/format.hpp"\n')
        o.append('#include "lvglpp/i18n/rltn.hpp"\n')
        o.append("\n#include <initializer_list>\n#include <string>\n")
    o.append(f"\nnamespace {namespace} {{\n\n")

    o.append("enum class Locale : std::uint8_t {\n")
    for i, (v, _) in enumerate(locale_variants):
        o.append(f"    {v} = {i},\n")
    o.append("};\n\n")
    o.append(f"inline constexpr std::uint8_t LOCALE_COUNT = {len(locales)};\n")
    o.append(f"inline constexpr Locale LOCALE_DEFAULT = "
             f"Locale::{locale_variants[0][0]};\n\n")

    o.append("enum class Key : std::uint16_t {\n")
    for i, (v, _) in enumerate(key_variants):
        o.append(f"    {v} = {i},\n")
    o.append("};\n\n")
    o.append(f"inline constexpr std::uint16_t KEY_COUNT = {len(keys)};\n\n")

    o.append("namespace detail {\n\n")
    o.append("inline constexpr const char* LOCALE_NAMES[] = {\n")
    for _, lname in locale_variants:
        o.append(f'    "{cxx_escape(lname)}",\n')
    o.append("};\n\n")
    o.append("inline constexpr const char* TAG_NAMES[] = {\n")
    for _, k in key_variants:
        o.append(f'    "{cxx_escape(k)}",\n')
    o.append("};\n\n")
    o.append("// Deliberately declared, never defined: referencing it in the\n"
             "// consteval key() below turns an unknown key into a\n"
             "// compile-time error (t! compile_error! parity under\n"
             "// -fno-exceptions).\n")
    o.append("void unknown_i18n_key();\n\n")
    o.append("}  // namespace detail\n\n")

    o.append("[[nodiscard]] constexpr const char* locale_name(Locale l) {\n")
    o.append("    return detail::LOCALE_NAMES[static_cast<std::uint8_t>(l)];\n")
    o.append("}\n\n")
    o.append("[[nodiscard]] constexpr const char* tag_name(Key k) {\n")
    o.append("    return detail::TAG_NAMES[static_cast<std::uint16_t>(k)];\n")
    o.append("}\n\n")
    o.append("// Compile-time key lookup: key(\"demo.title\") == Key::DemoTitle;\n"
             "// an unknown key fails to compile.\n")
    o.append("[[nodiscard]] consteval Key key(std::string_view tag) {\n")
    o.append("    for (std::uint16_t i = 0; i < KEY_COUNT; ++i) {\n")
    o.append("        if (tag == detail::TAG_NAMES[i]) "
             "return static_cast<Key>(i);\n")
    o.append("    }\n")
    o.append("    detail::unknown_i18n_key();\n")
    o.append("    return static_cast<Key>(0);\n")
    o.append("}\n")

    if emit_rltn:
        o.append("\nnamespace detail {\n")
        o.append("// external/static: built-in RLTN blob, rodata.\n")
        o.append(f'#include "{name}_rltn.inc"\n')
        o.append("}  // namespace detail\n\n")
        o.append("// Register the built-in blob; call once at startup before\n"
                 "// any t(). PARITY: rlvgl include_bytes! + BUILTIN_BLOB.\n")
        o.append("inline void init_rltn() {\n")
        o.append("    ::lvglpp::i18n::register_builtin(detail::RLTN_BLOB);\n")
        o.append("}\n\n")
        o.append("inline void set_locale(Locale l) {\n")
        o.append("    ::lvglpp::i18n::set_locale_index("
                 "static_cast<std::uint8_t>(l));\n")
        o.append("}\n\n")
        o.append("[[nodiscard]] inline Locale locale() {\n")
        o.append("    const std::uint8_t v = ::lvglpp::i18n::locale_index();\n")
        o.append("    return v < LOCALE_COUNT ? static_cast<Locale>(v) "
                 ": LOCALE_DEFAULT;\n")
        o.append("}\n\n")
        o.append("// PARITY: t!(\"key\") -> &'static str.\n")
        o.append("[[nodiscard]] inline std::string_view t(Key k) {\n")
        o.append("    return ::lvglpp::i18n::t_static_index("
                 "static_cast<std::uint16_t>(k));\n")
        o.append("}\n\n")
        o.append("// PARITY: t!(\"key\", name = value, ...) -> String.\n")
        o.append("[[nodiscard]] inline std::string t(Key k,\n")
        o.append("        std::initializer_list<::lvglpp::i18n::Param> "
                 "params) {\n")
        o.append("    return ::lvglpp::i18n::format(t(k), params);\n")
        o.append("}\n")

    o.append(f"\n}}  // namespace {namespace}\n")
    return "".join(o)


def emit_rltn_inc(blob: bytes) -> str:
    o = [GENERATED_NOTE]
    o.append(f"inline constexpr std::uint8_t RLTN_BLOB_BYTES[{len(blob)}] = {{\n")
    for i in range(0, len(blob), 12):
        row = ", ".join(f"0x{b:02x}" for b in blob[i:i + 12])
        o.append(f"    {row},\n")
    o.append("};\n")
    o.append("inline constexpr std::span<const std::uint8_t> RLTN_BLOB{"
             "RLTN_BLOB_BYTES};\n")
    return "".join(o)


def emit_lv_header(locales, keys, name, namespace):
    """lv_translation static pack + bridge wrappers.

    Layout per lv_translation_add_static (lv_translation.c:87–109):
    TRANSLATIONS is row-major by tag, language within row
    (translation_p[language_cnt * tag_idx + lang_idx]).
    docs/i18n/01-lv-translation-bridge.md §5.1–§5.2.
    """
    o = [GENERATED_NOTE]
    o.append("// Requires lvgl built with LV_USE_TRANSLATION 1; include\n"
             "// after the application's lvgl.h is reachable.\n")
    o.append("#pragma once\n\n")
    o.append(f'#include "{name}.hpp"\n\n')
    o.append('#include "lvglpp/i18n/lv_bridge.hpp"\n\n')
    o.append(f"namespace {namespace} {{\n\nnamespace detail {{\n\n")

    o.append("// external/static: lv_translation_add_static keeps these\n"
             "// pointers for the lifetime of the pack — rodata, never freed.\n")
    o.append("inline constexpr const char* LV_LANGUAGES[] = {\n")
    for lname, _ in locales:
        o.append(f'    "{cxx_escape(lname)}",\n')
    o.append("    nullptr,\n};\n\n")

    o.append("inline constexpr const char* LV_TAGS[] = {\n")
    for k in keys:
        o.append(f'    "{cxx_escape(k)}",\n')
    o.append("    nullptr,\n};\n\n")

    o.append("// Row-major by tag, language within row; no nullptr entries\n"
             "// (build-time fallback fill), so upstream's runtime fallback\n"
             "// chain never fires for this pack (docs/i18n/01 §5.1).\n")
    o.append("inline constexpr const char* LV_TRANSLATIONS[] = {\n")
    for k in keys:
        row = ", ".join(
            f'"{cxx_escape(mapping[k])}"' for _, mapping in locales)
        o.append(f"    {row},\n")
    o.append("};\n\n")
    o.append("}  // namespace detail\n\n")

    o.append(
        "// Register the generated static pack. Call once after lv_init()\n"
        "// (which runs lv_translation_init, lv_init.c:415).\n"
        "inline lv_translation_pack_t* init_lv_pack() {\n"
        "    return lv_translation_add_static(detail::LV_LANGUAGES,\n"
        "                                     detail::LV_TAGS,\n"
        "                                     detail::LV_TRANSLATIONS);\n"
        "}\n\n"
        "// Select the language and notify every widget on every display\n"
        "// (NULL-root tree walk — includes inactive screens and top/sys\n"
        "// layers). Labels given text via set_label_tag re-resolve and\n"
        "// self-invalidate; no manual redraw call is needed or correct\n"
        "// (docs/i18n/01 §5.3).\n"
        "// NOTE: independent of the RLTN core's set_locale — a consumer\n"
        "// using both prongs keeps them in sync itself (docs/i18n/01 §10).\n"
        "inline void set_language(Locale l) {\n"
        "    lv_translation_set_language(locale_name(l));\n"
        "}\n\n"
        "// Compile-checked tag lookup; pairs with consteval key(\"...\").\n"
        "// Returns: borrows pack rodata (or the tag itself pre-\n"
        "// set_language, upstream fallback).\n"
        "[[nodiscard]] inline const char* tr(Key k) {\n"
        "    return lv_tr(tag_name(k));\n"
        "}\n\n"
        "// Named-placeholder parameterization on top of lv_tr — the\n"
        "// capability upstream lv_translation lacks.\n"
        "[[nodiscard]] inline std::string tr_format(Key k,\n"
        "        std::initializer_list<::lvglpp::i18n::Param> params) {\n"
        "    return ::lvglpp::i18n::format(tr(k), params);\n"
        "}\n\n"
        "// The cooperative path for labels: stores the tag so the label\n"
        "// re-resolves on language change (lv_label.c:872–878).\n"
        "// Args:\n"
        "//   obj: borrows; must be an lv_label.\n"
        "inline void set_label_tag(lv_obj_t* obj, Key k) {\n"
        "    lv_label_set_translation_tag(obj, tag_name(k));\n"
        "}\n")

    o.append(f"\n}}  // namespace {namespace}\n")
    return "".join(o)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--locales", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--name", required=True)
    ap.add_argument("--namespace", default="lvglpp::i18n::gen")
    ap.add_argument("--emit", default="keys,rltn")
    args = ap.parse_args()

    emit = {e.strip() for e in args.emit.split(",") if e.strip()}
    unknown = emit - {"keys", "rltn", "lv"}
    if unknown:
        sys.exit(f"error: unknown --emit backend(s): {sorted(unknown)}")
    emit.add("keys")  # keys are the foundation of both other backends

    locales, keys = load_locales(args.locales)
    args.out.mkdir(parents=True, exist_ok=True)

    def write(path: Path, content):
        mode = "wb" if isinstance(content, bytes) else "w"
        # Only touch files whose content changed (CMake-friendly).
        if path.exists():
            old = path.read_bytes() if mode == "wb" else path.read_text()
            if old == content:
                return
        with open(path, mode) as f:
            f.write(content)

    if "rltn" in emit:
        blob = build_blob(locales, keys)
        write(args.out / f"{args.name}.bin", blob)
        write(args.out / f"{args.name}_rltn.inc", emit_rltn_inc(blob))

    write(args.out / f"{args.name}.hpp",
          emit_keys_header(locales, keys, args.name, args.namespace,
                           "rltn" in emit))

    if "lv" in emit:
        write(args.out / f"{args.name}_lv.hpp",
              emit_lv_header(locales, keys, args.name, args.namespace))


if __name__ == "__main__":
    main()
