// assets.cpp — icon-asset accessors over CMake-generated byte arrays.
//
// PARITY: rlvgl/examples/apps/disco-demo/src/assets.rs (v0.2.0 @ 79f730d).
// LVGL:   N/A (app composite asset table).
// DELTA:  rlvgl's `include_bytes!` statics become accessor functions over
//         arrays generated from the same `.rle` files at CMake-configure
//         time (consume-only — lvglpp never encodes assets).

#include "lvglpp/app/disco_demo/assets.hpp"

// Generated at CMake-configure time from the rlvgl icon `.rle` files.
// Defines lvglpp::app::disco_demo::detail::ICON_*_BYTES arrays. Configure
// FAILs (FATAL_ERROR) if any asset is missing, so these spans are never
// silently empty (DEMO-05 §3).
#include "disco_demo_assets.inc"

namespace lvglpp::app::disco_demo {

std::span<const std::uint8_t> icon_settings() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_SETTINGS_BYTES);
}
std::span<const std::uint8_t> icon_file() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_FILE_BYTES);
}
std::span<const std::uint8_t> icon_info() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_INFO_BYTES);
}
std::span<const std::uint8_t> icon_audio48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_AUDIO_48_BYTES);
}
std::span<const std::uint8_t> icon_camera48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_CAMERA_48_BYTES);
}
std::span<const std::uint8_t> icon_monitor48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_MONITOR_48_BYTES);
}
std::span<const std::uint8_t> icon_globe48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_GLOBE_48_BYTES);
}
std::span<const std::uint8_t> icon_bug48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_BUG_48_BYTES);
}
std::span<const std::uint8_t> icon_cpu48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_CPU_48_BYTES);
}
std::span<const std::uint8_t> icon_play48() noexcept {
    return std::span<const std::uint8_t>(detail::ICON_PLAY_48_BYTES);
}

}  // namespace lvglpp::app::disco_demo
